global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'curator'
    static_configs:
      - targets: ['curator:8000']

  - job_name: 'vectoriser'
    static_configs:
      - targets: ['vectoriser:8000']

  - job_name: 'professor'
    static_configs:
      - targets: ['professor:8000']

  - job_name: 'reviewer'
    static_configs:
      - targets: ['reviewer:8000']

  - job_name: 'tutor'
    static_configs:
      - targets: ['tutor:8000']

  - job_name: 'auditor'
    static_configs:
      - targets: ['auditor:8000']

  - job_name: 'custodian'
    static_configs:
      - targets: ['custodian:8000']

  - job_name: 'governor'
    static_configs:
      - targets: ['governor:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']

  - job_name: 'elasticlite'
    static_configs:
      - targets: ['elasticlite:9200']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
